### ISSUE TITLE
[Suggestion] Backport to 1.20.x

### ISSUE THREAD

**Issue by PixitOwO** [KosmoMoustache/MusicNotification#28]
I beg of you to please add compatibility for 1.20.x with the newest version. I would love to add custom sprites but I can't since the modpack I have is on 1.20.1. I love the mod, super simple and clean!

**Comment by cpgyuri** [comment]
Yes please to this suggestion. I have made a music resource pack compatible with this mod for the small smp I have with friends (server in Minecraft 1.20.1 because of the mods we use), but it doesn't read the musics.json file on my resourcepack because that feature is only available for the 1.20.4 version of your mod. Most people make this mods compatible for all 1.20.X versions, we will be very thankful if you could make this possible!

**Comment by KosmoMoustache** [comment]
Thank you for your patience, the mod is available for Minecraft 1.20.1-6
