### ISSUE TITLE
confusion regarding disc sprites

### ISSUE THREAD

**Issue by OrangeSniper** [KosmoMoustache/MusicNotification#62]
Where do I put custom disc sprites? I tried assets/musicnotification/textures/gui/sprites/toast/that_expanse.png and it failed to use it.

**Comment by OrangeSniper** [comment]
this is on version 1.20.1-2.0.1

**Comment by KosmoMoustache** [comment]
I've added easy custom disc sprites only in 1.20.2, for this version you need to replace the toast textures (/assets/musicnotification/textures/gui/toasts.png) and add your custom discs below the existing one. And in your musics.json instead of using `cover` you need to specify the x and y coordinate of your disc using `coverTextureSlotX` and `coverTextureSlotY`.

I've made an example resource pack that can be found [here](https://github.com/KosmoMoustache/MusicNotification/tree/1.20.1/test) and the docs for this version [here](https://github.com/KosmoMoustache/MusicNotification/blob/1.20.1/DOCS.md)
